name: example
description: A practical demonstration of the Absolute Rule Architecture and Linter.
publish_to: none

environment:
  sdk: ^3.3.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  clean_feature_arch:
    path: ../
  lints: ^3.0.0
